---
- include: fedora.yml
  when: is_rhel7.rc != 0

- include: rhel7.yml
  when: is_rhel7.rc == 0

- name: write the global config file
  template: src=config.j2 dest=/etc/kubernetes/config
  notify:
          - restart daemons

- name: write the service script file
  copy: src={{ item }} dest=/usr/lib/systemd/system/{{ item }} owner=root group=root mode=0644
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-proxy.service
    - kube-scheduler.service
    - kubelet.service

- name: collect facts about the version of kubernetes
  kube-caps:
