---
- name: write the service script file
  copy: src={{ item }} dest=/usr/lib/systemd/system/{{ item }} owner=root group=root mode=0644
  with_items:
    - kube-proxy.service
    - kubelet.service

- name: write the config files for kubelet
  template: src=kubelet.j2 dest=/etc/kubernetes/kubelet
  when: not kubelet_use_pre_v10_vars
  notify:
          - restart kubelet

- include: kubelet-old.yaml
  when: kubelet_use_pre_v10_vars

- name: write the config files for proxy
  template: src=proxy.j2 dest=/etc/kubernetes/proxy
  notify:
          - restart proxy

- name: Start kubelet process (This is workaround)
  shell: nohup /usr/bin/kubelet --logtostderr=true --v=3 --api_servers=http://{{ master_ip_address }}:8080 --address=0.0.0.0 --hostname_override={{ inventory_hostname }} --allow_privileged=true &
  async: 45
  poll: 0

#- name: Enable kubelet
#  service: name=kubelet enabled=yes state=started

- name: Enable proxy
  service: name=kube-proxy enabled=yes state=started

- include: firewalld.yml
  when: has_firewalld.rc == 0

- include: iptables.yml
  when: has_firewalld.rc != 0 and has_iptables.rc == 0
